# Generated by Django 2.2.17 on 2020-11-11 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20201111_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255, verbose_name='カメラの製造元')),
                ('model', models.CharField(max_length=255, verbose_name='カメラのモデル')),
            ],
            options={
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.Device'),
        ),
    ]
