# Generated by Django 2.2.17 on 2020-11-15 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201112_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Place'),
        ),
    ]
