# Generated by Django 2.2.17 on 2020-11-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201115_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='alt',
            field=models.FloatField(null=True),
        ),
    ]
