# Generated by Django 2.2.17 on 2020-11-16 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_place_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exif', models.TextField(default='{}', verbose_name='exifデータ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoMeta',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aperture', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='絞り値')),
                ('exposure_bias', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('exposure_mode', models.CharField(blank=True, max_length=16, verbose_name='')),
                ('exposure_program', models.CharField(blank=True, max_length=16, verbose_name='露出プログラム')),
                ('exposure_time', models.CharField(blank=True, max_length=16, verbose_name='露出時間')),
                ('flash', models.BooleanField(blank=True, null=True)),
                ('flash_mode', models.CharField(blank=True, max_length=16)),
                ('f_number', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='絞り値')),
                ('focal_length', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='レンズ焦点距離')),
                ('iso_speed_ratings', models.IntegerField(blank=True, null=True)),
                ('metering_mode', models.CharField(blank=True, max_length=32)),
                ('shutter_speed', models.CharField(blank=True, max_length=16)),
                ('white_blance', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='shooting_datetime',
            field=models.DateTimeField(null=True, verbose_name='撮影日時'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Exif'),
        ),
        migrations.AddField(
            model_name='photo',
            name='meta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.PhotoMeta'),
        ),
    ]
