# Generated by Django 2.2.17 on 2020-12-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20201116_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='dest_bear',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='h_positioning_error',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='img_dir',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.Device'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Exif'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.PhotoMeta'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Place'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shooting_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撮影日時'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
