# Generated by Django 2.2.17 on 2021-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20201207_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='dest_bear_ref',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='img_dir_ref',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
